name: hquplink
description: 'A free app and resource for the Star Wars: Legion community'
version: 0.1.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.0.8
  built_collection: ^4.1.0
  built_value: ^6.2.0
  cupertino_icons: ^0.1.2
  device_id: ^0.1.3
  firebase_auth: ^0.6.6
  flake_uuid: ^0.1.3
  google_sign_in: ^3.2.4
  package_info: 0.3.2
  path: ^1.6.2
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  swlegion:
    git: https://github.com/hquplink/swlegion

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  built_value_generator: ^6.2.0
  mockito: ^4.0.0
  test: ^1.5.1+1

flutter:
  assets:
    - assets/
    - assets/dice/attack/
    - assets/dice/defense/
    - assets/cards/
    - assets/factions/
    - assets/ranks/
    - assets/upgrades/
  uses-material-design: true
